### ISSUE TITLE
The value of the fetched data changes when the time_zone is set.

### ISSUE THREAD

**Issue by nanaBaah** [volueinsight/wapi-python#104]
Hello,

Please can you tell me why the value of the actual data changes when the time_zone='UTC' in __get_data()__?
Or I do not understand the purpose of the parameter?
Because this does not happened when __output_timezone__ is rather used instead of __time_zone__.

Can you please explain this to me?

Below is the example:
----
### This is first code with no time_zone parameter (default = CET):

```python
session = wapi.Session(config_file=my_config_file)

start_date = pd.Timestamp('2020-6-1 00:00')
end_date =  pd.Timestamp('2020-6-8 00:00')

curve_name = 'tt de con °c cet min15 s'
curve = session.get_curve(name=curve_name)
ts = curve.get_data(
    data_from=start_date, 
    data_to=end_date,
)
df_cet = ts.to_pandas().to_frame(name='value')
```
----

### df_cet output:

![image](https://user-images.githubusercontent.com/12661590/184534969-1ede21f1-266b-4218-abed-3bf22b808ced.png)
----

#### Additional info about the dataframe:

![image](https://user-images.githubusercontent.com/12661590/184535393-9dc7bd6c-9b7c-45da-b0b2-edbff7e5a794.png)

----
----

#### This is the second code with time_zone set to __'UTC'__
```python
session = wapi.Session(config_file=my_config_file)
start_date = pd.Timestamp('2020-6-1 00:00')
end_date =  pd.Timestamp('2020-6-8 00:00')

curve_name = 'tt de con °c cet min15 s'
curve = session.get_curve(name=curve_name)
ts = curve.get_data(
    data_from=start_date, 
    data_to=end_date,
    time_zone='UTC'
)
df_utc = ts.to_pandas().to_frame()
```
----

#### df_utc output:

![image](https://user-images.githubusercontent.com/12661590/184534985-f9302ce4-484a-4a4b-a561-5952b088a87c.png)
----

#### Additional info about the dataframe:
![image](https://user-images.githubusercontent.com/12661590/184535068-6f2c7f26-189c-4347-a18a-5f1a20323a0b.png)

**Comment by hieuhc** [comment]
I don't think we could say the values have changed just by looking at your printed outputs, because those two reflect different set of timestamps.

Say for example first row of first output, _2020-06-01 00:00:00+02:00_ is not the same at _2020-06-01 00:00:00+00:00_, as in the fist row of the second output. Instead in UTC, it would be equal to _2020-05-31 22:00:00+00:00_, whose value was not showed there. In fact, there was no overlapping in timestamp in your provided outputs.
