### ISSUE TITLE
cannot import name 'Iterable' from 'collections' in python 3.10+

### ISSUE THREAD

**Issue by rogarui** [volueinsight/wapi-python#159]
The Iterable was removed from collections in Python 3.10.
Change that line into

`from collections.abc import Iterable`

**Comment by deep-volue** [comment]
Thank you for your feedback. "wapi-python" library is not tested against Python versions higher than 3.9. Instead, we have a successor library which supports higher versions of Python.
https://github.com/volueinsight/volue-insight-timeseries
