### ISSUE TITLE
FutureWarning: 'T' is deprecated and will be removed in a future version

### ISSUE THREAD

**Issue by PApostol** [volueinsight/wapi-python#162]
Using `wapi-python==0.7.13` with `pandas>=2.2.0` in Python 3.10, results in this warning:

`wapi/util.py:135: FutureWarning: 'T' is deprecated and will be removed in a future version, please use 'min' instead.`

The warning comes from converting a `wapi.util.TS` object to a `pandas.Series` object [here](https://github.com/volueinsight/wapi-python/blob/0ff299347ac4817754d1e2eb59b8132f3e71c661/wapi/util.py#L135).

**Comment by deep-volue** [comment]
This issue will be handled in our upcoming python package which is meant to support higher versions of Python (3.10 onwards)

**Comment by deep-volue** [comment]
We have a successor of wapi-python in which this issue should be solved. It also supports higher versions of Python.
https://github.com/volueinsight/volue-insight-timeseries
