### ISSUE TITLE
Make package available to Python 3.7+

### ISSUE THREAD

**Issue by jankislinger** [volueinsight/wapi-python#83]
Hi, could you please make the package on pypi repository avaiable for new versions of Pyrhon? It blocks using newer versions of other packages as well. For example, pandas 1.2 requires at least Python 3.7.1. I just tested your package with Python 3.7.10 and it passed all tests so it looks like the upgrade will be smooth.

**Comment by stigalvestad** [comment]
We are working on a new version, which will support newer python versions. Estimated to be available in beta version within a month or so.

**Comment by deep-volue** [comment]
We have released https://github.com/volueinsight/volue-insight-timeseries which supports latest versions of Python now.
